version: '3'
services: 
  api-manstock:
    container_name: api-manstock
    image: api-manstock
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports: 
      - 3000:3000
    volumes:
      - /home/app
    command: npm run start